module.exports = {
  protocol: "https://",
  baseUrl: "devapi.influenz.club/v1/client/",
  userLogin: "signin",
  userSignup: "signup",
  forgotPassword: "forgot",
  transactionList: "transaction/list",
  campaign: "campaign/",
  campaignList: "campaign/list",
  campaignAnalytics: "campaign/analytics",
  campaignRecharge: "campaign/recharge",
  campaignRechargeList: "campaign/recharge/list",
  campaignStatus: "campaign/status",
  campaignMoveCharge: "campaign/movecharge",
};
